version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    expose:
      - 3000
    ports:
      - '3000:3000'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 3001
    ports:
      - '3001:3001'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
